import Head from "next/head";
import Image from "next/image";
import Slider from "../components/Slider";
import styles from "../styles/Home.module.css";
import Doctor from "../components/Doctor";
import DetailsCabinet from "../components/DetailsCabinet";
import Horaires from "../components/Horaires";
import Stories from "../components/Stories";
import RendezVous from "../components/RendezVous";
import ServiceCarousel from "../components/ServiceCarousel";
export default function Home() {
  return (
    <>
      <Head>
        <title>Cabinet Dentiste Tunisie | Dentiste Chirurgien tunisie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="canonical" href="https://tunisie-dentiste.tn" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&display=swap" />
      </Head>
      <br />
      <Slider />

      <Doctor title={true} />
      <DetailsCabinet />
      <ServiceCarousel />
      <RendezVous />
      <Stories />
      <Horaires />
    </>
  );
}
